apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "wordpress.name" . }}
    helm.sh/chart: {{ include "wordpress.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wordpress.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wordpress.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if .Values.podLabels }}
        ## Custom pod labels
        {{- range $key, $value := .Values.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- if .Values.podAnnotations }}
        ## Custom pod annotations
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /run-nginx.sh
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /nginx-status
              port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: config-volume
            subPath: nginx.conf
          - mountPath: /app/wp-config.php
            name: config-volume
            subPath: wp-config.php
          resources:
{{ toYaml .Values.resources | indent 12 }}
        - name: {{ .Chart.Name }}-php-fpm
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /run-php.sh
          env:
          - name: MYSQL_HOST
          {{- if .Values.mariadb.enabled }}
            value: {{ template "mariadb.fullname" . }}
          {{- else }}
            value: {{ .Values.externalDatabase.host | quote }}
          {{- end }}
          - name: MYSQL_PORT
          {{- if .Values.mariadb.enabled }}
            value: "3306"
          {{- else }}
            value: {{ .Values.externalDatabase.port | quote }}
          {{- end }}
          - name: MYSQL_DATABASE
          {{- if .Values.mariadb.enabled }}
            value: {{ .Values.mariadb.db.name | quote }}
          {{- else }}
            value: {{ .Values.externalDatabase.database | quote }}
          {{- end }}
          - name: MYSQL_USER
          {{- if .Values.mariadb.enabled }}
            value: {{ .Values.mariadb.db.user | quote }}
          {{- else }}
            value: {{ .Values.externalDatabase.user | quote }}
          {{- end }}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- if .Values.mariadb.enabled }}
                name: {{ template "mariadb.fullname" . }}
                key: mariadb-password
              {{- else }}
                name: {{ printf "%s-%s" .Release.Name "externaldb" }}
                key: db-password
              {{- end }}
          - name: WP_OFFLOAD_BUCKET
            value: {{ .Values.offload.bucket | quote }}
          - name: WP_OFFLOAD_REGION
            value: {{ .Values.offload.region | quote }}
          - name: WP_OFFLOAD_DOMAIN
            value: {{ .Values.offload.domain | quote }}
          - name: WP_OFFLOAD_CLOUDFRONT
            value: {{ .Values.offload.cloudfront | quote }}
          ports:
            - name: fpm
              containerPort: 9000
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /fpm-ping
          #    port: http
          volumeMounts:
          - mountPath: /etc/php/7.2/fpm/php-fpm.conf  
            name: config-volume
            subPath: fpm.conf
          - mountPath: /etc/php/7.2/fpm/pool.d/www.conf
            name: config-volume
            subPath: fpm-pool.conf
          - mountPath: /app/wp-config.php
            name: config-volume
            subPath: wp-config.php
          resources:
{{ toYaml .Values.resources | indent 12 }}
        - name: {{ .Chart.Name }}-php-fpm-monitor
          image: "{{ .Values.exporter.phpfpm.image.repository }}:{{ .Values.exporter.phpfpm.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.phpfpm.image.pullPolicy }}    
          env:
          - name: PHP_FPM_WEB_LISTEN_ADDRESS
            value: {{ .Values.exporter.phpfpm.listenaddress | quote }}
          - name: PHP_FPM_WEB_TELEMETRY_PATH
            value: {{ .Values.exporter.phpfpm.metrics | quote }}
          - name: PHP_FPM_SCRAPE_URI
            value: {{ .Values.exporter.phpfpm.scrape_uri | quote }}
          - name: PHP_FPM_FIX_PROCESS_COUNT 
            value: {{ .Values.exporter.phpfpm.fix_process_count | quote }}
          - name: PHP_FPM_LOG_LEVEL
            value: {{ .Values.exporter.phpfpm.log_level | quote }}
          ports:
            - name: listenaddress
              containerPort: 9253
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: listenaddress
          resources:
{{ toYaml .Values.resources | indent 12 }}
#        - name: {{ .Chart.Name }}-nginx-monitor
#          image: "{{ .Values.exporter.nginx.image.repository }}:{{ .Values.exporter.nginx.image.tag }}"
#          imagePullPolicy: {{ .Values.exporter.nginx.image.pullPolicy }}
#          env:
#          - name: nginx_stub_status
#            value: {{ .Values.exporter.nginx.stub_status | quote }}
#          - name: nginx_scrape_port_uri
#            value: {{ .Values.exporter.nginx.scrape_port | quote }}
#          - name: nginx_metrics
#            value: {{ .Values.exporter.nginx.metrics | quote }}
#          ports:
#            - name: listenaddress
#              containerPort: 9253
#              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /metrics
#              port: listenaddress
#          resources:
#{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: config-volume
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: {{ include "wordpress.fullname" . }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
