{{- if .Values.external_secret.enabled }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ template "wordpress.fullname" . }}
  labels:
    app: "{{ template "wordpress.fullname" . }}"
    chart: "{{ template "wordpress.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "0"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
secretDescriptor:
  backendType: {{ .Values.external_secret.backendType }}
  data:
  {{- range $key, $value := .Values.external_secret.mapping }}
    - key: {{ $value }}
      name: {{ $key }}
  {{- end }}
{{- end }}