apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wordpress.fullname" . }}-install
  labels:
    app.kubernetes.io/name: {{ include "wordpress.name" . }}
    helm.sh/chart: {{ include "wordpress.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: job-done
        image: busybox
        command: ['sh', '-c', 'echo "all jobs completed"']      
      initContainers:
      - name: wordpress-install-core
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        workingDir: /app
        command:
        - /install-core.sh
        env:
        - name: MYSQL_HOST
        {{- if .Values.mariadb.enabled }}
          value: {{ template "mariadb.fullname" . }}
        {{- else }}
          value: {{ .Values.externalDatabase.host | quote }}
        {{- end }}
        - name: MYSQL_PORT
        {{- if .Values.mariadb.enabled }}
          value: "3306"
        {{- else }}
          value: {{ .Values.externalDatabase.port | quote }}
        {{- end }}
        - name: MYSQL_DATABASE
        {{- if .Values.mariadb.enabled }}
          value: {{ .Values.mariadb.db.name | quote }}
        {{- else }}
          value: {{ .Values.externalDatabase.database | quote }}
        {{- end }}
        - name: MYSQL_USER
        {{- if .Values.mariadb.enabled }}
          value: {{ .Values.mariadb.db.user | quote }}
        {{- else }}
          value: {{ .Values.externalDatabase.user | quote }}
        {{- end }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
            {{- if .Values.mariadb.enabled }}
              name: {{ template "mariadb.fullname" . }}
              key: mariadb-password
            {{- else }}
              name: {{ printf "%s-%s" .Release.Name "externaldb" }}
              key: db-password
            {{- end }}
        {{- if .Values.externalDatabase.root_user }}
        - name: MYSQL_ROOT_USER
          value: {{ .Values.externalDatabase.root_user | quote }}
        {{- end }}
        {{- if .Values.externalDatabase.root_password }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "externaldb" }}
              key: db-root-password
        {{- end }}
        - name: WP_OFFLOAD_BUCKET
          value: {{ .Values.offload.bucket | quote }}
        - name: WP_OFFLOAD_REGION
          value: {{ .Values.offload.region | quote }}
        - name: WP_OFFLOAD_DOMAIN
          value: {{ .Values.offload.domain | quote }}
        - name: WP_OFFLOAD_CLOUDFRONT
          value: {{ .Values.offload.cloudfront | quote }}
        - name: WP_DEFAULT_HOST
          value: {{ index .Values.ingress.hosts 0 | quote }}
        - name: WORDPRESS_FIRSTNAME
          value: {{ .Values.wordpressFirstName | quote }}
        - name: WORDPRESS_LASTNAME
          value: {{ .Values.wordpressLastName | quote }}
        - name: WORDPRESS_BLOGNAME
          value: {{ .Values.wordpressBlogName | quote }}
        - name: WORDPRESS_BLOGURL
          value: {{ index .Values.ingress.hosts 0 | quote }}
        - name: WORDPRESS_EMAIL
          value: {{ .Values.wordpressEmail | quote }}
        - name: WORDPRESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ template "wordpress.fullname" . }}
              key: wordpress-username
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "wordpress.fullname" . }}
              key: wordpress-password
        volumeMounts:
          - mountPath: /etc/php/7.2/fpm/php-fpm.conf
            name: config-volume
            subPath: fpm.conf
          - mountPath: /etc/php/7.2/fpm/pool.d/www.conf
            name: config-volume
            subPath: fpm-pool.conf
          - mountPath: /app/wp-config.php
            name: config-volume
            subPath: wp-config.php
      - name: wordpress-activate-plugins
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        workingDir: /app
        command:
        - /activate-plugins.sh
        env:
        - name: MYSQL_HOST
        {{- if .Values.mariadb.enabled }}
          value: {{ template "mariadb.fullname" . }}
        {{- else }}
          value: {{ .Values.externalDatabase.host | quote }}
        {{- end }}
        - name: MYSQL_PORT
        {{- if .Values.mariadb.enabled }}
          value: "3306"
        {{- else }}
          value: {{ .Values.externalDatabase.port | quote }}
        {{- end }}
        - name: MYSQL_DATABASE
        {{- if .Values.mariadb.enabled }}
          value: {{ .Values.mariadb.db.name | quote }}
        {{- else }}
          value: {{ .Values.externalDatabase.database | quote }}
        {{- end }}
        - name: MYSQL_USER
        {{- if .Values.mariadb.enabled }}
          value: {{ .Values.mariadb.db.user | quote }}
        {{- else }}
          value: {{ .Values.externalDatabase.user | quote }}
        {{- end }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
            {{- if .Values.mariadb.enabled }}
              name: {{ template "mariadb.fullname" . }}
              key: mariadb-password
            {{- else }}
              name: {{ printf "%s-%s" .Release.Name "externaldb" }}
              key: db-password
            {{- end }}
        - name: WP_OFFLOAD_BUCKET
          value: {{ .Values.offload.bucket | quote }}
        - name: WP_OFFLOAD_REGION
          value: {{ .Values.offload.region | quote }}
        - name: WP_OFFLOAD_DOMAIN
          value: {{ .Values.offload.domain | quote }}
        - name: WP_OFFLOAD_CLOUDFRONT
          value: {{ .Values.offload.cloudfront | quote }}
        - name: WP_OFFLOAD_LOCAL_DOMAINS
          value: {{ .Values.offload.local_domains | quote }}
        - name: WP_DEFAULT_HOST
          value: {{ index .Values.ingress.hosts 0 | quote }}
        - name: WP_PLUGINS
          value: {{ include "wordpress.joinListWithSpace" .Values.plugins }}
        volumeMounts:
        - mountPath: /etc/php/7.2/fpm/php-fpm.conf
          name: config-volume
          subPath: fpm.conf
        - mountPath: /etc/php/7.2/fpm/pool.d/www.conf
          name: config-volume
          subPath: fpm-pool.conf
        - mountPath: /app/wp-config.php
          name: config-volume
          subPath: wp-config.php
      restartPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: {{ include "wordpress.fullname" . }}
  backoffLimit: 4
