apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wordpress.fullname" . }}-migrate
  labels:
    app.kubernetes.io/name: {{ include "wordpress.name" . }}
    helm.sh/chart: {{ include "wordpress.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: job-done
        image: busybox
        command: ['sh', '-c', 'echo "all jobs completed"']      
      initContainers:
{{- if ( .Values.offload.bucket ) }}
      - name: wordpress-migrate-amazon-s3
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        workingDir: /app
        command:
        - /migrate-amazon-s3.sh
        env:
        - name: MYSQL_HOST
        {{- if .Values.mariadb.enabled }}
          value: {{ template "mariadb.fullname" . }}
        {{- else }}
          value: {{ .Values.externalDatabase.host | quote }}
        {{- end }}
        - name: MYSQL_PORT
        {{- if .Values.mariadb.enabled }}
          value: "3306"
        {{- else }}
          value: {{ .Values.externalDatabase.port | quote }}
        {{- end }}
        - name: MYSQL_DATABASE
        {{- if .Values.mariadb.enabled }}
          value: {{ .Values.mariadb.db.name | quote }}
        {{- else }}
          value: {{ .Values.externalDatabase.database | quote }}
        {{- end }}
        - name: MYSQL_USER
        {{- if .Values.mariadb.enabled }}
          value: {{ .Values.mariadb.db.user | quote }}
        {{- else }}
          value: {{ .Values.externalDatabase.user | quote }}
        {{- end }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
            {{- if .Values.mariadb.enabled }}
              name: {{ template "mariadb.fullname" . }}
              key: mariadb-password
            {{- else }}
              name: {{ printf "%s-%s" .Release.Name "externaldb" }}
              key: db-password
            {{- end }}
        - name: WP_OFFLOAD_BUCKET
          value: {{ .Values.offload.bucket | quote }}
        - name: WP_OFFLOAD_REGION
          value: {{ .Values.offload.region | quote }}
        - name: WP_OFFLOAD_DOMAIN
          value: {{ .Values.offload.domain | quote }}
        - name: WP_OFFLOAD_CLOUDFRONT
          value: {{ .Values.offload.cloudfront | quote }}
        - name: WP_DEFAULT_HOST
          value: {{ index .Values.ingress.hosts 0 | quote }}
        volumeMounts:
          - mountPath: /etc/php/7.2/fpm/php-fpm.conf
            name: config-volume
            subPath: fpm.conf
          - mountPath: /etc/php/7.2/fpm/pool.d/www.conf
            name: config-volume
            subPath: fpm-pool.conf
          - mountPath: /app/wp-config.php
            name: config-volume
            subPath: wp-config.php
{{ end }}
      restartPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: {{ include "wordpress.fullname" . }}
  backoffLimit: 4